// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {db} from '../models';
import {service} from '../models';

export function ClearAllLogs():Promise<void>;

export function DeleteUser(arg1:string):Promise<void>;

export function ExportFiscalYearLogsCSV(arg1:number):Promise<string>;

export function ForceExitAllInside():Promise<number>;

export function GetAllUsers():Promise<Array<db.RegisteredUser>>;

export function GetCurrentInsideUsers():Promise<Array<db.UserStatus>>;

export function GetDashboardStats():Promise<db.DashboardStats>;

export function GetRecentLogs(arg1:number):Promise<Array<db.AccessLog>>;

export function ImportLogsCSV():Promise<string>;

export function ImportUsersCSV():Promise<string>;

export function ProcessSwipe(arg1:string):Promise<service.SwipeResponse>;

export function SaveUser(arg1:db.RegisteredUser):Promise<void>;

export function ToggleFullscreen():Promise<boolean>;

export function VerifyPIN(arg1:string):Promise<boolean>;
