// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearAllLogs() {
  return window['go']['main']['App']['ClearAllLogs']();
}

export function DeleteUser(arg1) {
  return window['go']['main']['App']['DeleteUser'](arg1);
}

export function ExportFiscalYearLogsCSV(arg1) {
  return window['go']['main']['App']['ExportFiscalYearLogsCSV'](arg1);
}

export function ForceExitAllInside() {
  return window['go']['main']['App']['ForceExitAllInside']();
}

export function GetAllUsers() {
  return window['go']['main']['App']['GetAllUsers']();
}

export function GetCurrentInsideUsers() {
  return window['go']['main']['App']['GetCurrentInsideUsers']();
}

export function GetDashboardStats() {
  return window['go']['main']['App']['GetDashboardStats']();
}

export function GetRecentLogs(arg1) {
  return window['go']['main']['App']['GetRecentLogs'](arg1);
}

export function ProcessSwipe(arg1) {
  return window['go']['main']['App']['ProcessSwipe'](arg1);
}

export function SaveUser(arg1) {
  return window['go']['main']['App']['SaveUser'](arg1);
}

export function VerifyPIN(arg1) {
  return window['go']['main']['App']['VerifyPIN'](arg1);
}
